apiVersion: v1
kind: ReplicationController
metadata:
  name: quote-store-controller
  labels:
    app: quote-api
    role: persistent-storage
spec:
  replicas: 1
  selector:
    app: quote-api
    role: persistent-storage
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        app: quote-api
        role: persistent-storage
    spec:
      containers:
      - name: master
        image: redis
        ports:
          - containerPort: 6379
        volumeMounts:
        - name: quote-store-volume
          mountPath: /data/redis
      volumes:
      - name: quote-store-volume
        emptyDir: {}
